spring:
  profiles:
    group:
      local: local-mysql
      dev: dev-mysql
      prod: prod-mysql
---
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  endpoint:
    metrics:
      cache:
        time-to-live: 30s
