spring:
  cache:
    type: redis
    multilevel:
      time-to-live: 10m
      local:
        max-size: 2000
        expiry-jitter: 50
  profiles:
    group:
      local: local-mysql
      dev: dev-mysql
      prod: prod-mysql

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
---
