spring:
  profiles:
    group:
      local: local-mysql
      dev: dev-mysql
      prod: prod-mysql
---
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  endpoint:
    metrics:
      cache:
        time-to-live: 30s
    env.enabled: true
    health:
      enabled: true
      show-details: always
    info.enabled: true
    loggers.enabled: true
    mappings.enabled: true
    metrics.enabled: true
    prometheus.enabled: true
