spring:
  application:
    name: anipick-backend
---
mybatis:
  mapper-locations: mapper/**/*.xml
---
spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
---
jwt:
  secret-key: ${SECRET_KEY}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}
  
anime:
  default-cover-url: ${ANIME_DEFAULT_COVER_URL}

app:
  oauth2:
    google:
      android-client-id: ${ANDROID_CLIENT_ID}
      ios-client-id: ${IOS_CLIENT_ID}