spring:
  profiles:
    group:
      local: local-mysql
      dev: dev-mysql
      prod: prod-mysql

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
---
